name: 网易云签到刷歌

on: 
  schedule:
    - cron: '0 */12 * * *'
  watch:
    types: [started]
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run
      run: |
        python netease_music.py > out.log
      env: 
        netease_username: ${{ secrets.NETEASE_USER }}
        netease_password: ${{ secrets.NETEASE_PWD }}
        SECRETKEY: ${{ secrets.SECRETKEY }}
    - name: Upload result file
      uses: actions/upload-artifact@master
      with:
        name: result
        path: ./*.log
