# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 什么值得买签到

on: 
  release:
    types: [published]
  push:
    tags:
      - 'v*'
    branches: 
      - main
  schedule:
    - cron: '* 1 * * *'
  watch:
    types: [started]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run
      run: |
        python smzdm.py > out.log
      env: 
        SMZDM_COOKIES: ${{ secrets.SMZDM_COOKIE }}
    - name: Upload result file
      uses: actions/upload-file@master
      with:
        name: result
        path: ./*.log
