name: 天使动漫打工

on: 
  schedule:
    - cron: '0 */1 * * *'
  watch:
    types: [started]
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python #安装python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install requirements #安装模块
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: start
      run: |
        python tsdm_dg.py
      env: 
        COOKIETS: ${{ secrets.COOKIETS }}
