# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 天使动漫签到

on: 
  schedule:
    - cron: '0 */4 * * *'
  watch:
    types: [started]
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run
      run: |
        echo '${{ secrets.COOKIETS }}' > ~/tsdm.cookies.txt
        python tsdm_qd.py -t tsdm ~/tsdm.cookies.txt > out.log
